// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: echo.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	echo.proto

It has these top-level messages:
	In
	Out
*/
package proto

import proto1 "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var EnumMessageType = struct {
	UnKnown MessageType
	A       MessageType
	B       MessageType
}{
	UnKnown: 0,
	A:       1,
	B:       2,
}
